name: Auction Monitor

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  test-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Send test notification
        run: |
          curl \
            -H "Title: Auction Monitor Test" \
            -H "Priority: default" \
            -d "GitHub successfully triggered your auction monitor!" \
            "https://ntfy.sh/${{ secrets.NTFY_TOPIC }}"
